### PR TITLE
Update to Easy Breakfast Taco Recipe

### PR DESCRIPTION
**Pull request by nnadams87**
## 🎯 Objective

Create Breakfast Taco Recipes
Use this URL for the recipe:
https://downshiftology.com/recipes/easy-breakfast-tacos/

## 🛠️ Changes made

Changed title of recipe to Easy Breakfast Tacos

## 👥 Who needs to review this Pull Request? 

@syousuf3 @BasimSiddiqui or anyone else!
_Pull Requests should include commits from each member of your group._

### CODE REVIEW

**Review by nnadams87 — COMMENTED** [review]
Looks great! @syousuf3 can you review/approve?

**Review by nnadams87 — COMMENTED** [review]
Looks great, thank you! @syousuf3 can you please approve/review?

**Review by smallyn9 — APPROVED** [review]
Hell yes to breakfast tacos!

**Review by nnadams87 — COMMENTED** [review]
Looks great! @syousuf3 can you please provide 2nd review?

**Review by nnadams87 — COMMENTED** [review]
Looks great! @syousuf3 can you please provide 2nd review?

**Review by smallyn9 — COMMENTED** [review]
Nice adds! I'm not totally sure I understand the code I'm seeing. For some reason, the timing is in red. Do you know if you deleted that?

**Review by smallyn9 — APPROVED** [review]
I'm really happy this has bacon :)

**Review by syousuf3 — APPROVED** [review]
Looks great.

**Review by syousuf3 — APPROVED** [review]
Thumbs up.

**Review by syousuf3 — APPROVED** [review]
LGTM!

**Comment by syousuf3** [comment]
Hi Nicole,

I reviewed your pull request

**Comment by BasimSiddiqui** [comment]
Good job team! 🙌🙌🙌

**Review by BasimSiddiqui — COMMENTED** [review]
Better and more intuitive title for sure 👍

**Pull request merged**
